###

GET http://localhost:8080/banners.save?id=0&title=title1&content=content1&button=button1&link=link1 HTTP/1.1
Accept: application/json
X-CustomHeader: custom header

###
GET http://localhost:8080/banners.save?id=1&title=title2&content=content1&button=button1&link=link1 HTTP/1.1
###
GET http://localhost:8080/banners.save?id=0&title=title2&content=content2&button=button2&link=link2 HTTP/1.1

###
GET http://localhost:8080/banners.removeByID?id=1 HTTP/1.1

###
GET http://localhost:8080/banners.getAll HTTP/1.1